# Generated by Django 5.0.4 on 2024-04-23 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='avalible',
            new_name='available',
        ),
    ]
